language: java
jdk:
  - openjdk11

branches:
  only:
    - manju # 해당하는 브랜치

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy: # deploy 명령어가 실행되기전 수행
  - mkdir -p before-deploy # zip에 포함시킬 파일들ㅇ르 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: manju-issue-test # S3 버킷 명칭
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on: # S3 전송을 위한 명령어
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: manju-issue-test
    key: webservice.zip
    bundle_type: zip # 압축 확장자

    application: webservice-test
    deployment_group: webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on: # S3 전송을 위한 명령어
      all_branches: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jhc1426@naver.com
